### ISSUE TITLE
Service fails to find go.mod for certgen

### ISSUE THREAD

**Issue by kastl-ars** [openSUSE/obs-service-go_modules#50]
Another instance of the service not finding the go.mod file:

https://github.com/minio/certgen/tree/v1.3.0

```
Running source_service 'go_modules' ...
INFO:obs-service-go_modules:Running OBS Source Service: obs-service-go_modules
INFO:obs-service-go_modules:Autodetecting archive since no archive param provided in _service
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.tar.gz
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.tar.xz
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.tar.zst
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.tar.lz
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.tar.bz2
DEBUG:obs-service-go_modules:Trying to find archive name with pattern certgen*.obscpio
INFO:obs-service-go_modules:Archive autodetected at /XXX/certgen/certgen-1.3.0.obscpio
INFO:obs-service-go_modules:Using archive certgen-1.3.0.obscpio
INFO:obs-service-go_modules:Extracting certgen-1.3.0.obscpio to /tmp/tmpvu5q022p
INFO:obs-service-go_modules:Switching to /tmp/tmpvu5q022p
ERROR:obs-service-go_modules:File go.mod not found under /tmp/tmpvu5q022p/certgen
Aborting: service call failed:  /usr/lib/obs/service/go_modules --basename certgen --subdir ./ --outdir /XXX/certgen/tmphyblrqfd.go_modules.service
```

The basename was incorrectly detected as  `certgen/.github`, but even with setting the basename and the subdir it still fails.

```
  <service name="go_modules" mode="manual">
    <param name="basename">certgen</param>
    <param name="subdir">./</param>
  </service>
```

**Comment by johanneskastl** [comment]
Hmmm, seems like the `basename_from_archive` function looks for only directories within the tarball. And it only finds one: `.github`.

If I change the order, in which the functions are being called, then the basename detection seems to work:

```        basename = (                                                                                                                        
            args.basename                                                                                                                   
            or basename_from_archive_name(archive)                                                                                          
            or basename_from_archive(archive)                                                                                               
        )

```

**Comment by johanneskastl** [comment]
Hmmm, it could simply be because the `go.mod` file for certgen does not have any dependencies init:

https://github.com/minio/certgen/blob/main/go.mod

```
module github.com/minio/certgen

go 1.21
```

I would propose that the service errors out with a useful message instead of this (which I got when using the modified service from #51):

```
INFO:obs-service-go_modules:Vendor go.mod dependencies to vendor.tar.gz
Traceback (most recent call last):
  File "/usr/lib/obs/service/go_modules", line 322, in <module>
    main()
  File "/usr/lib/obs/service/go_modules", line 315, in main
    new_archive.add_files(vendor_dir)
  File "/usr/lib/python3.11/site-packages/libarchive/write.py", line 84, in add_files
    r = read_next_header2(read_p, entry_p)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libarchive/ffi.py", line 98, in check_int
    raise archive_error(args[0], retcode)
libarchive.exception.ArchiveError: vendor: Cannot stat (errno=2, retcode=-25, archive_p=94160168216544)
```

**Comment by johanneskastl** [comment]
The changes from #51 seem to do the trick in this case, at least it then leads to #52... :-)
